### ISSUE TITLE
Add a CONTRIBUTING

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/docs#12]
I wanted to serve the docs for my PR, but I got stuck with the error:

![Screenshot from 2020-01-19 00-39-20](https://user-images.githubusercontent.com/1448289/72677711-27588d00-3a54-11ea-9ed6-a825e463f670.png)

Would be nice to know how we can develop / contribute to the docs and preview it :smile:

**Comment by dcodeIO** [comment]
If I'm not mistaken there are two versions of GitBook. The open source one, which they do not support anymore, and the newer as-a-service one, that we use. Looks like some of the v2 features can't be rendered by earlier versions? I wonder if they even have an intended preview feature for v2. Usually updating the Docs on gitbook.com's web editor, which I can add you to, but not everyone, hmm.

**Comment by torch2424** [comment]
@dcodeIO Oh that's quite interesting, When I get the chance, I'll look into how we can have both? 🤔

**Comment by dcodeIO** [comment]
Fixed by moving to the new website. The contributing guidelines are now linked within the top navbar under "Community".
