### ISSUE TITLE
"😏" emoji is ambiguous on https://docs.assemblyscript.org/basics

### ISSUE THREAD

**Issue by mdempsky** [AssemblyScript/docs#4]
At https://docs.assemblyscript.org/basics, there's explanations about TypeScript types that can't be used in AssemblyScript. However, the examples don't use English to explain which ones are acceptable vs not: they only use emojis.

The "😢" and "😊" emojis that are used three times each are straight forward.

However, "😏" is used only once for the "class A" example where objects must be strictly typed. I *think* using classes like this would be an instance of strict typing, but the emoji is ambiguous to me. In my browser (Chrome on Linux), it looks a lot like "😑", which suggests to me disappointment; i.e., that the example would be invalid.

**Comment by dcodeIO** [comment]
Thanks, just changed that one to the "😊" emoji as well.

**Comment by mdempsky** [comment]
Thanks! I appreciate the quick fix!
