### ISSUE TITLE
Offline Version

### ISSUE THREAD

**Issue by ohenepee** [AssemblyScript/docs#6]
Is there a way to get an offline version?

**Comment by dcodeIO** [comment]
One can theoretically clone the repository and read the md files offline, potentially using a program that displays markdown syntax a bit prettier. Not all GitBook features will work, though. Not sure if they have or plan to make an offline feature (would doubt, tho).

**Comment by dcodeIO** [comment]
GitBook meanwhile introduced a feature to export the docs as PDF. There's a link to do this on the top-right now.
